name: Build svelte app to dist/
on:
  push:
    branches:
      - master
concurrency:
  group: "cd"
  cancel-in-progress: true

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        env:
          GITHUB_TOKEN: ${{ secrets.HUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
      - name: Build
        run: npm install && npm run build
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          git commit -m "(build) Build svelte"
          git push
